version: "3.5"

services:
  backend:
    image: "social_map/backend:0.1.0"
    build: ./backend
    ports:
      - 8000:8000
    command: [ 'python', 'run_server.py' ]
  #    environment:
  #      DB_URL: postgres://login:password@host:port/db
  frontend:
    image: "social_map/frontend:0.1.0"
    build: ./webapp-i1
    ports:
    - 5000:5000
    command: ['python', 'app.py']
